# Define the minimal Fastlane version
fastlane_version "1.41.1"

# Use the iOS platform as default
default_platform :ios

# Define what to do for the iOS platform
platform :ios do

 before_all do
    
  end

   desc "Runs all the tests"
  lane :test do
    
  end


end