# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
#opt_out_usage

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.33.6"


###########################################################################
desc "Will build all active schemes"
lane :ALL do
	QA()
	PROD()
end


desc "Create QA IPA"
lane :QA do
	build(
		scheme: 'QA', 
      	filename_prefix: 'FastFedEx',
      	config_plist_path: './FastFedEx/Configuration/Strings_Env_QA.plist',
    )
end

desc "Create PROD IPA"
lane :PROD do
	build(
		scheme: 'PROD', 
      	filename_prefix: 'FastFedEx',
      	config_plist_path: './FastFedEx/Configuration/Strings_Env_PROD.plist',
    )
end

desc "Create QA IPA only"
lane :QA_IPA do
	build_just_ipa(
		scheme: 'QA', 
      	filename_prefix: 'FastFedEx',
      	config_plist_path: './FastFedEx/Configuration/Strings_Env_QA.plist'
    )
end
###############################################################################


desc "Create Lane to perform the build commands"
private_lane :build do |options|

	XCODE_SCHEME = options[:scheme]
	IPA_PREFIX = options[:filename_prefix]
	PLIST_PATH = options[:config_plist_path]
		
	puts '-----------------------------------'
	puts '- P A S S E D   V A R I A B L E S -'
	puts '-----------------------------------'
	puts 'XCODE_SCHEME=' + XCODE_SCHEME
	puts 'PLIST_PATH=' + PLIST_PATH
	puts 'IPA_PREFIX=' + IPA_PREFIX
	puts '-----------------------------------'	
	
	
    XCODE_TEAM_ID = ''
    XCODE_SIGN_ID = 'iPhone Distribution:.'
    XCODE_PROVISIONING_PROFILE_PATH = './fastlane/' + XCODE_SCHEME  + '.mobileprovision'
    
    puts 'XCODE_PROVISIONING_PROFILE_PATH=' + XCODE_PROVISIONING_PROFILE_PATH
	puts '-----------------------------------'
	VERSION_NUMBER =  2
	BUILD_NUMBER = 2
	XCODE_IPA_NAME = IPA_PREFIX + '_'	+ XCODE_SCHEME + '_' + VERSION_NUMBER.to_s + '_' + BUILD_NUMBER.to_s

	HOCKEY_API_TOKEN = get_info_plist_value(path: PLIST_PATH, key: 'HOCKEY_API_TOKEN')

	BUILD_SERVER_URL = sh('hostname')
	

	puts '-----------------------------------'
	puts '--- R E A D   V A R I A B L E S ---'
	puts '-----------------------------------'
	puts 'XCODE_SCHEME=' + XCODE_SCHEME	
	puts 'PLIST_PATH=' + PLIST_PATH
	puts 'IPA_PREFIX=' + IPA_PREFIX
	puts 'XCODE_IPA_NAME=' + XCODE_IPA_NAME
	puts 'XCODE_PROVISIONING_PROFILE_PATH=' + XCODE_PROVISIONING_PROFILE_PATH
	puts 'XCODE_TEAM_ID=' + XCODE_TEAM_ID
	puts 'XCODE_SIGN_ID=' + XCODE_SIGN_ID
	
	puts 'VERSION_NUMBER=' + VERSION_NUMBER.to_s
	puts 'BUILD_NUMBER=' + BUILD_NUMBER.to_s

	puts 'HOCKEY_API_TOKEN=' + HOCKEY_API_TOKEN
	puts 'BUILD_SERVER_URL=' + BUILD_SERVER_URL
	puts '-----------------------------------'
	
	puts '-----------------------------------'
	puts '--- G Y M  -  I P A  &  D S Y M ---'
	puts '-----------------------------------'
	

       puts '-----------------------------------'
	puts '----------- Crashlytics -----------'
	puts '-----------------------------------'	

       crashlytics(api_token: "e5151d636f965b3d6b941585c9a8f7cf96242df6",
              build_secret: "05a33bcb37febd1880108fa2f7eaa1809cbaf68b41d5a6904899e0cdd7789bc8")
	
	
end

desc "after_all - This lane is called, only if the executed lane was successful"
after_all do |lane|

	puts '-----------------------------------'
	puts '-C L E A N U P   A R T I F A C T S-'
	puts '-----------------------------------'
	
	#File.delete('../../' + XCODE_IPA_NAME + '.ipa')
    #File.delete('../../' + XCODE_IPA_NAME + '.app.dSYM.zip')

	notification(message: "Fastlane finished '#{lane}' successfully") # Mac OS X Notification
end

desc "Lane error handling"
error do |lane, exception|
    notification(message: "Fastlane '#{lane}' errored, #{exception}") # Mac OS X Notification
end 


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md