default_platform :ios


platform :ios do

  before_all do
    #cocoapods
    #increment_build_number
    gym(scheme: “FastFedEx”)

   hockey(
      api_token: “d89f76b741df4c29be03e8700ca333f8”,
      #public_identifier: HOCKEY_APP_ID,
      notes: "Changelog",
      notify: '0',
      #notes:git_branch + ' (Uploaded via fastlane).'
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(device: "iPhone 6s")
  end

  after_all do |lane|

  end

  error do |lane, exception|
    say "error in lane! "
  end

end